### PR TITLE
Supernova: Merge of Mission Supernova Engine

### PR DESCRIPTION
**Pull request by Joefish**
This PR adds support for "Mission Supernova Teil 1".

- Game is completable
- Translation for part 1 and 2 is done but needs to be polished
- Scrolling text is missing
- Intro music reverb still buggy

Before doing any big code refactoring I would like to port part 2 first. When I tried removing the brightness fade in at state.cpp:GameManager::executeRoom() +2279 to fix an outro bug it broke at so many places in unexpected ways that I was worried how it will affect the progress of porting part 2.
Also, I uploaded a playthrough of [part 1](https://www.youtube.com/watch?v=ge3mmnaKrYQ).
Tested on Linux 4.14.5-1-ARCH x64.

Looking forward to your suggestions!

### CODE REVIEW

**Comment by dafioram** [comment]
I can't build this PR on my linux machine:
engines/supernova/supernova.cpp:141:42: error: no matching function for call to ‘initGraphics(int&, int&)’
engines/supernova/supernova.cpp:439:44: error: no matching function for call to ‘initGraphics(int&, int&)’
engines/supernova/supernova.cpp:445:44: error: no matching function for call to ‘initGraphics(int&, int&)’

If I remove your last commit (8c54b1d) it builds.

**Comment by wjp** [comment]
That last commit should have been done after a merge of master into this branch.

**Comment by Joefish** [comment]
I used my working branch for the PR (base commit from May 30th) instead of creating an extra branch and rebasing it on the most recent upstream commit. As I wrote in the commit message, 432fd52 removed the scalar flag for initGraphics() and thus broke my PR.
So I changed it to pass the buildbot, although it broke my local branch.

I am sorry for the inconveniences it has caused..

@wjp wouldn't the merge cause a conflict as it would try to reapply the upstream commits again on the main branch?

**Comment by wjp** [comment]
No.

**Comment by dafioram** [comment]
Can you have the engine close gracefully if supernova.dat isn't found rather than seg faulting?

**Comment by sev-** [comment]
@Joefish You did the merge a bit incorrectly. What you need to do is to rebase:

First, follow these instructions and get your master synced with scummvm/master: https://help.github.com/articles/syncing-a-fork/

After that, do:
```
  git checkout supernova
  git rebase master
  <resolve conflicts if any, commit if needed>
  git push -f  (you have to force push because you are changing history)
```
If you need help with it or want me to do it, just provide me the access to your repository.

**Comment by wjp** [comment]
Rebasing this will take a bit more effort, since without integrating this `initGraphics` patch into the full history, we will end up with uncompilable commits. I'd suggest leaving this step until after the review stage.

**Comment by sev-** [comment]
@wjp, good point, I kind of missed that part

File: engines/supernova/state.h [hunk 1]
```diff
@@ -0,0 +1,234 @@
...
+#ifndef STATE_H
+#define STATE_H
+
+#include "common/rect.h"
+#include "common/keyboard.h"
+#include "supernova/rooms.h"
+
+namespace Supernova {
+
+const int32 INT32_MAX = 0x7FFFFFFF;
```
Comment (bgK) [inline engines/supernova/state.h]: This does not compile on my system using GCC 7.2.1 because `INT32_MAX` is already defined:
```
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/7.2.1/include/stdint.h:9:0,
                 from /usr/include/inttypes.h:27,
                 from /usr/include/SDL2/SDL_stdinc.h:69,
                 from /usr/include/SDL2/SDL_endian.h:31,
                 from /scummvm/common/scummsys.h:309,
                 from /scummvm/common/func.h:26,
                 from /scummvm/gui/debugger.h:26,
                 from /scummvm/engines/supernova/console.cpp:23:
/scummvm/engines/supernova/state.h:32:13: error: expected unqualified-id before numeric constant
 const int32 INT32_MAX = 0x7FFFFFFF;
```

File: engines/supernova/supernova.cpp [hunk 2]
```diff
@@ -0,0 +1,1152 @@
...
+		if (_screenWidth != 640) {
+			_screenWidth = 640;
+			_screenHeight = 480;
+			initGraphics(_screenWidth, _screenHeight);
+		}
+	} else {
+		if (_screenWidth != 320) {
+			_screenWidth = 320;
+			_screenHeight = 200;
+			initGraphics(_screenWidth, _screenHeight);
```
Comment (bgK) [inline engines/supernova/supernova.cpp]: Since the engine seems to switch modes between 320x200 and 640x480 perhaps it should declare to the backend the list of used modes using `initGraphicsModes` so the backend can choose a suited window size.

File: engines/supernova/supernova.cpp [hunk 3]
```diff
@@ -0,0 +1,1152 @@
...
+{
+	if (filenumber != 49 && filenumber != 52) {
+		return;
+	}
+
+	int index = filenumber == 49 ? 0 : 1;
+	Audio::AudioStream *audioStream = Audio::makeProtrackerStream(_soundMusic[index]);
+	stopSound();
+	_mixer->playStream(Audio::Mixer::kMusicSoundType, &_soundHandle, audioStream,
+	                   -1, Audio::Mixer::kMaxChannelVolume, 0, DisposeAfterUse::NO);
```
Comment (bgK) [inline engines/supernova/supernova.cpp]: `DisposeAfterUse::NO` this looks like a memory leak.

File: engines/supernova/supernova.h [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+	void renderRoom(Room &room);
+	void renderMessage(const char *text, MessagePosition position = kMessageNormal);
+	void removeMessage();
+	void renderText(const char *text, int x, int y, byte color);
+	void renderText(const uint16 character, int x, int y, byte color);
+	void renderText(const char *text);
+	void renderText(const uint16 character);
+	void renderBox(int x, int y, int width, int height, byte color);
+	void setColor63(byte value);
+	void command_print();
```
Comment (bgK) [inline engines/supernova/supernova.h]: Not implemented and not used.

File: engines/supernova/state.cpp [hunk 5]
```diff
@@ -0,0 +1,2383 @@
...
+			_vm->renderText(_guiInventoryArrow[1]._text,
+			                _guiInventoryArrow[1]._textPosition.x,
+			                _guiInventoryArrow[1]._textPosition.y,
+			                _guiInventoryArrow[1]._textColor);
+		}
+	}
+}
+
+uint16 GameManager::getKeyInput(bool blockForPrintChar) {
+	while (true) {
```
Comment (bgK) [inline engines/supernova/state.cpp]: Consider checking `_vm->shouldQuit()`

File: engines/supernova/supernova.cpp [hunk 6]
```diff
@@ -0,0 +1,1152 @@
...
+
+	if (_gm->_state._alarmOn && _gm->_state._timeAlarm <= _gm->_state._time) {
+		_gm->_state._alarmOn = false;
+		_gm->alarm();
+		return;
+	}
+
+	_gm->_mouseClicked = false;
+	_gm->_keyPressed = false;
+	while (g_system->getEventManager()->pollEvent(_event)) {
```
Comment (bgK) [inline engines/supernova/supernova.cpp]: `_event` could seemingly be a local variable to reduce confusion.

File: engines/supernova/state.h [hunk 7]
```diff
@@ -0,0 +1,234 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+ * GNU General Public License for more details.
+ *
+ * You should have received a copy of the GNU General Public License
+ * along with this program; if not, write to the Free Software
+ * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
+ *
+ */
+
+#ifndef STATE_H
```
Comment (bgK) [inline engines/supernova/state.h]: Include guards should be prefixed with the engine name.

**Comment by bgK** [comment]
I quickly skimmed through the code and this looks good to me. Kudos to everybody involved! :+1:

File: engines/supernova/rooms.cpp [hunk 8]
```diff
@@ -0,0 +1,3241 @@
...
+	_vm->renderText(title1, 78 - _vm->textWidth(title1) / 2, 120, kColorLightBlue);
+	_vm->renderText(title2, 78 - _vm->textWidth(title2) / 2, 132, kColorWhite99);
+	_vm->renderText(title3, 78 - _vm->textWidth(title3) / 2, 142, kColorWhite99);
+	_gm->wait2(1);
+	CursorMan.showMouse(true);
+	_vm->playSoundMod(kMusicIntro);
+	_gm->getInput();
+	// TODO: render animated text
+	_vm->playSound(kAudioVoiceYeah);
+	while (_vm->_mixer->isSoundHandleActive(_vm->_soundHandle));
```
Comment (bgK) [inline engines/supernova/rooms.cpp]: Busy waiting is not good. Consider at least delaying and polling for events; and possibly updating the screen.

There are a few other instances of busy-waiting on `isSoundHandleActive` in this file that should be fixed.

File: engines/supernova/supernova.h [hunk 9]
```diff
@@ -0,0 +1,208 @@
...
+	Common::RandomSource *_rnd;
+	GameManager *_gm;
+	Console *_console;
+	Audio::SoundHandle _soundHandle;
+	ScreenBufferStack _screenBuffer;
+	byte _mouseNormal[256];
+	byte _mouseWait[256];
+	MSNImageDecoder *_currentImage;
+	struct SoundSample {
+		byte *_buffer;
```
Comment (bgK) [inline engines/supernova/supernova.h]: These pointers should be initialized to `nullptr` at `SupernovaEngine` construction time to avoid freeing garbage pointers in the destructor.

Comment (csnover) [reply engines/supernova/supernova.h]: With regards to memory management, I would even recommend that, throughout, (1) things that can be made members of the engine object itself should (e.g. `SupernovaEngine::_rnd`), since this avoids unnecessary small heap allocations, and (2) anything else which doesn’t need to be copyable and which owns heap-allocated memory (like `SoundSample::_buffer`) should use `Common::ScopedPtr` (for objects) or `Common::Array` (for collections of things, including bytes) and not a raw pointer, since this provides much better guarantees against leaks, missing initialisations, double-frees, and frees of garbage memory.

**Comment by dafioram** [comment]
I was able to get through part 1 without any issues (except swallowing the egg the first time).

**Comment by Joefish** [comment]
Thanks a lot everyone for your suggestions!

@dafioram yea first time it also took me a bit to try opening it instead. :)

**Comment by criezy** [comment]
For this game we are using our translations web site to handle the translation to English. That way anybody can contribute and make suggestions to improve the translation. Some polishing has already been done for the first part, and I have now pushed an updated data file with all the latest changes, but I am sure it can still be improved.
https://translations.scummvm.org/#list-games

This can also be used if anybody wants to work on a translation to a different language. The engine data file format should already support adding translations to additional languages, but we may need to extend the tool  to generate it and modify the engine if we need to store fonts in it (to allow customising the font).

There is still a few changes on my list for this engine, and most notably changing the way loading/saving is handled during the dream sequence, but overall I am quite happy with the state of the engine.

And a shameless plug with links to a couple of blogs that contain posts about the development of this engine:
Joefish's GSoC blog: https://joefish-gsoc.blogspot.co.uk
My blog: http://criezy.blogspot.co.uk/search/label/Mission%20Supernova

**Comment by criezy** [comment]
I think this can be merged now, but I would welcome suggestions on how to handle the rebase in relation to the change of the initGraohics API.

**Comment by tsoliman** [comment]
> I would welcome suggestions on how to handle the rebase in relation to the change of the initGraohics API.

An interactive rebase, with edits marked for the commits affected by the initGraphics changes, would make it as if the changes were always against the new API.

What I usually do is have 2 branches. One branch is the regular "merge" branch, the other branch is the rebase branch. Once the rebase is done I `git diff mergebranch rebasebranch` to make sure they are identical and nothing was lost in the rebase. This also has the nice side effect of providing an easy place to `git reset --hard` to if I need to redo the rebase (if all else fails)

**Comment by Joefish** [comment]
I just discovered a nice way of finding the commits in question:
> git log supernova --not master -S"initGraphics("

Also 9719128 can be removed as it's just a merge of master.

**Comment by dreammaster** [comment]
Regarding the git log trick you posted, bless you. I'd been meaning for a
while to rebase my legend branch against master, but kept putting it off
because I wasn't sure how to easily figure out which commits had
intiGraphics calls in them. And since the engine has gone through several
revisions of the core systems over time, there were multiple different
commits with initGraphics. Now I've got a nice cleaned up commit history
that compiles at every step of the way :)

DreamMaster.

**Comment by criezy** [comment]
Thanks to the suggestion from tsoliman and some help from wjp and snover, I now have a rebased supernova branch with rewritten history so that every commit compiles:
https://github.com/criezy/scummvm/commits/supernova-rebased

I will merge it tomorrow (unless someone objects) when my brain is in working order.

**Comment by criezy** [comment]
This code has now been merged.
