### PR TITLE
AGS: added steam achievements for Resonance and others

### PR DESCRIPTION
**Pull request by mgerhardy**
https://store.steampowered.com/app/212050/Resonance/

Also see this PR: https://github.com/scummvm/scummvm/pull/2814

With this Resonance is starting now and no longer errors out due to missing achievement functions. I've not tested the other games.

~~Beware - there is UTF-8 in the descriptions - how to handle this?~~ (converted to hex encoding)

### CODE REVIEW

File: engines/ags/achievements_tables.h [hunk 1]
```diff
@@ -91,7 +91,358 @@ static const AchievementDescriptionList achievementDescriptionList[] = {
...
+		"253110",
+		{
+			ACHIEVEMENT_SIMPLE_ENTRY("CHAPTER_1", "Chapter 1 Completed!", "Complete the first chapter."),
+			ACHIEVEMENT_SIMPLE_ENTRY("CHAPTER_2", "Chapter 2 Completed!", "Complete the second chapter."),
+			ACHIEVEMENT_SIMPLE_ENTRY("CHAPTER_3", "Chapter 3 Completed!", "Complete the third chapter."),
+			ACHIEVEMENT_SIMPLE_ENTRY("CHAPTER_4", "Chapter 4 Completed!", "Complete the fourth chapter."),
+			ACHIEVEMENT_SIMPLE_ENTRY("CHAPTER_5", "Chapter 5 Completed!", "Complete the fifth chapter."),
+			ACHIEVEMENT_SIMPLE_ENTRY("CHAPTER_6", "Chapter 6 Completed!", "Complete the sixth chapter."),
+			ACHIEVEMENT_SIMPLE_ENTRY("CHAPTER_7", "Chapter 7 Completed!", "Complete the final chapter."),
+			ACHIEVEMENT_SIMPLE_ENTRY("REWARD", "The Great Reward", "Hidden."),
```
Comment (mgerhardy) [inline engines/ags/achievements_tables.h:309]: Should we use `ACHIEVEMENT_HIDDEN_ENTRY` for these?

File: engines/ags/achievements_tables.h [hunk 2]
```diff
@@ -91,7 +91,358 @@ static const AchievementDescriptionList achievementDescriptionList[] = {
...
+		Common::STEAM_ACHIEVEMENTS,
+		"631570",
+		{
+			ACHIEVEMENT_SIMPLE_ENTRY("CaseClosed", "Case Closed", "Finished the game"),
+			ACHIEVEMENT_SIMPLE_ENTRY("PathOfTyr", "Path of Tyr", "Finished the game assertively"),
+			ACHIEVEMENT_SIMPLE_ENTRY("PathOfFrigg", "Path of Frigg", "Finished the game analytically"),
+			ACHIEVEMENT_SIMPLE_ENTRY("PathOfBaldr", "Path of Baldr", "Finished the game empathically"),
+			ACHIEVEMENT_SIMPLE_ENTRY("UnlockTier2", "Hidden Potential", "Unlocked a new augmentation"),
+			ACHIEVEMENT_SIMPLE_ENTRY("UnlockAugs", "Power Overwhelming", "Unlocked a full set of augmentations"),
+			ACHIEVEMENT_SIMPLE_ENTRY("Harbinger", "Singularity-Minded", "Hidden."),
```
Comment (mgerhardy) [inline engines/ags/achievements_tables.h:408]: `ACHIEVEMENT_HIDDEN_ENTRY` for these?

File: engines/ags/achievements_tables.h [hunk 3]
```diff
@@ -91,7 +91,358 @@ static const AchievementDescriptionList achievementDescriptionList[] = {
...
+		"theterribleoldman",
+		Common::STEAM_ACHIEVEMENTS,
+		"1147030",
+		{
+			ACHIEVEMENT_SIMPLE_ENTRY("Beer", "Three for Two", "That's quite a deal!"),
+			ACHIEVEMENT_SIMPLE_ENTRY("Jackson", "Jackson", "We all have our dreams."),
+			ACHIEVEMENT_SIMPLE_ENTRY("Address", "Location uncovered!", "The old man won't know what hit him."),
+			ACHIEVEMENT_SIMPLE_ENTRY("Unlocked", "Unlocked", "What's in the trunk?"),
+			ACHIEVEMENT_SIMPLE_ENTRY("OpenSesame", "Open Sesame", "The riches are within grasp."),
+			ACHIEVEMENT_SIMPLE_ENTRY("TheEnd", "The End.", "Hidden."),
```
Comment (mgerhardy) [inline engines/ags/achievements_tables.h:441]: `ACHIEVEMENT_HIDDEN_ENTRY` for this one?

File: engines/ags/detection_tables.h [hunk 4]
```diff
@@ -1712,20 +1712,20 @@ const AGSGameDescription GAME_DESCRIPTIONS[] = {
 	GAME_ENTRY("qfi", "agsgame.dat", "2a0ba29e479ca5aa8c6b4233f030e78f", 536391599),
 	GAME_ENTRY("qfi", "agsgame.dat", "2a0ba29e479ca5aa8c6b4233f030e78f", 536513114), // Steam Linux
 	GAME_ENTRY("resonance", "resonance.exe", "2e635c22bcbf0ed3d46f1bcde71812d4", 849404957), // GOG
-	GAME_ENTRY("resonance", "resonance.exe", "2e635c22bcbf0ed3d46f1bcde71812d4", 849410915), // Steam
-	GAME_ENTRY("richardandalice", "richardandalice.exe", "1023d348f67ba958f78ed62d029565c7", 109164768), // Steam
-	GAME_ENTRY("richardandalice", "richardandalice.exe", "f47d11397e2059a25b11057ea6cf3409", 108264256), // Steam
+	GAME_ENTRY_PLUGIN_PLATFORM("resonance", "resonance.exe", "2e635c22bcbf0ed3d46f1bcde71812d4", 849410915, AGSTEAM_BLACKWELL, "Steam"), // Steam
```
Comment (mgerhardy) [inline engines/ags/detection_tables.h:1715]: `AGSTEAM_BLACKWELL` or the normal agsteam plugin? How to find out?

File: engines/ags/achievements_tables.h [hunk 5]
```diff
@@ -91,7 +91,358 @@ static const AchievementDescriptionList achievementDescriptionList[] = {
...
+			ACHIEVEMENTS_LISTEND
+		}
+	},
+
+	{
+		"samaritan",
+		Common::STEAM_ACHIEVEMENTS,
+		"283180",
+		{
+			ACHIEVEMENT_SIMPLE_ENTRY("ACH_GREEN_FINGERS", "Green Fingers", "Hidden."),
```
Comment (mgerhardy) [inline engines/ags/achievements_tables.h:208]: `ACHIEVEMENT_HIDDEN_ENTRY` for these?

File: engines/ags/achievements_tables.h [hunk 6]
```diff
@@ -91,7 +91,358 @@ static const AchievementDescriptionList achievementDescriptionList[] = {
...
+			ACHIEVEMENT_SIMPLE_ENTRY("trophy_patriot_games", "PATRIOT GAMES", "Maintained 100% patriot approval for five consecutive turns."),
+			ACHIEVEMENT_SIMPLE_ENTRY("trophy_wolf_of_wall_street", "THE WOLF OF WALL STREET", "Maintained 100% capitalist approval for five consecutive turns."),
+			ACHIEVEMENT_SIMPLE_ENTRY("trophy_signs", "SIGNS", "Maintained 100% fundamentalist approval for five consecutive turns."),
+			ACHIEVEMENT_SIMPLE_ENTRY("trophy_roger_and_me", "ROGER AND ME", "Maintained 100% liberal approval for five consecutive turns."),
+			ACHIEVEMENT_SIMPLE_ENTRY("trophy_chicken_run", "CHICKEN RUN", "Master the language of Emperor Roosti."),
+			ACHIEVEMENT_SIMPLE_ENTRY("trophy_the_kingdom", "THE KINGDOM", "Survived the 'Oil Theocracy' scenario."),
+			ACHIEVEMENT_SIMPLE_ENTRY("trophy_money_talks", "MONEY TALKS", "Survived the 'Capitalist Playground' scenario."),
+			ACHIEVEMENT_SIMPLE_ENTRY("trophy_persepolis", "PERSEPOLIS", "Survived the 'Unstable Elements' scenario."),
+			ACHIEVEMENT_SIMPLE_ENTRY("trophy_the_interview", "THE INTERVIEW", "Survived the 'Hermit Kingdom' scenario."),
+			ACHIEVEMENT_SIMPLE_ENTRY("trophy_be_blood", "THERE WILL BE BLOOD", "Hidden."),
```
Comment (mgerhardy) [inline engines/ags/achievements_tables.h:195]: `ACHIEVEMENT_HIDDEN_ENTRY` entry for these?

File: engines/ags/detection_tables.h (hunk 4 above)
Comment (SupSuper) [reply engines/ags/detection_tables.h:1715]: Only way is to test them. By default it should be the normal plugin. If it still has unresolved import errors on startup, then it needs the Blackwell plugin.

Comment (mgerhardy) [reply engines/ags/detection_tables.h:1715]: Then I will change it to the default plugin and we have to wait for feedback from people who own those games.

**Comment by dreammaster** [comment]
UTF8 in comments are fine, because compilers ignore them, but if they're in strings, that's an issue. It would be best if you properly used \x escaping to specify the characters instead

**Comment by mgerhardy** [comment]
UTF8 chars are converted now.

**Comment by mgerhardy** [comment]
Closing this one. The achievements should work independently from the detection entries. The list of achievements was added to `master` but the detection entries will just be ignored for now. This also means, that the just added achievements don't work yet. As the extra info of the detection entry was used in `AGSMetaEngine::getAchievementsInfo` to check the achievement platform.
