### PR TITLE
GLK SCOTT: Add graphics support for Questprobe: The Hulk.

### PR DESCRIPTION
**Pull request by StableSteady**
Updates the current SCOTT engine to support non SCOTTFREE games. Currently only the ZX Spectrum port of Questprobe: The Hulk is fully supported.

### CODE REVIEW

**Comment by dreammaster** [comment]
Kudos. I'll start reviewing it tonight., One thing, though.. could you do an interactive rebase and reword each commit message to add "GLK: SCOTT: " in front of each? This is a formatting requirement.

**Comment by einstein95** [comment]
Unable to build using clang version 13.0.1 on Linux
```
../engines/glk/scott/bsd.h:29:46: error: unknown type name 'size_t'
int xstrncasecmp(const char *, const char *, size_t);
                                             ^
../engines/glk/scott/bsd.cpp:51:50: error: unknown type name 'size_t'
int xstrncasecmp(const char *s1, const char *s2, size_t n) {
                                                 ^
2 errors generated.
```

Even after adding `#include <cstdint>` and `#include <stddef.h>` to these files it fails (full build log attached: [build.log](https://github.com/scummvm/scummvm/files/8428733/build.log))
```
engines/glk/scott/bsd.h
engines/glk/scott/decompress_text.h
engines/glk/scott/decompress_z80.h
engines/glk/scott/detect_game.h
engines/glk/scott/saga_draw.h
```

**Comment by PaulGilbert** [comment]
As a result of a quick scan before starting work, I also noticed a bsd.cpp/.h inclusion with a few string methods and the BSD license. I'd like to avoid muddying the waters with extra licenses other than GPL. Plus, I think equivalents to these methods are available from common/algorithm.h. scumm_stricmp and scumm_strincmp if I remember correctly. Which I presume were originally pinched from the scumm engine, given their prefix :)
