### PR TITLE
COMMON: Replace type detection in configure with aliases for stdint.h types

### PR DESCRIPTION
**Pull request by ccawley2011**
Now that `inttypes.h` is included on all platforms, we can use those types as aliases for our own types. This avoids the complexity of detecting the sizes of types in `configure` and provides better defaults when using other build systems (`create_project`, libretro, etc.) Platforms where this is an issue can specify alternative types in the backend's `portdefs.h` file.

A workaround has been left in place for AmigaOS and MorphOS, but I'm hoping that both of them use long for `int32_t` and `uint32_t`, which would allow the workaround to be removed. (CC @raziel-, @BeWorld2018).

### CODE REVIEW

**Comment by raziel-** [comment]
will test asap

thank you

**Comment by dwatteau** [comment]
@ccawley2011 I like the general idea, but it looks like the intentional PR #4557 hack is now gone, is it?

https://github.com/scummvm/scummvm/pull/6024/files#diff-c9485c5996fa68bdc00bc5b9967faf2af0381887cbd89e8d4cb576db6cdfc3be

The idea was to keep the `typedef signed long int32;` on win32, so that a frequent development platform + Github Actions target tests this `long` path. Having it at the Github Action stage, instead of the buildbot stage, helped catching and fixing some portability issues way sooner (“shifting left” in CI terms).

So I think that it would be nice to have the win32 keep the `typedef` exception as well. It has the side effect of helping the AmigaOS (and Nintendo DS?) target.

**Comment by raziel-** [comment]
it still builds, but i get a bunch-load of new format warnings now, is that meant to happen?

**Comment by raziel-** [comment]
@ccawley2011 

full build, all engines,  tried with three different engines

works fine

**Comment by dwatteau** [comment]
> it still builds, but i get a bunch-load of new format warnings now, is that meant to happen?

@raziel- I wouldn't think so... can you provide such logs (as an attachment, if they're large), at least in partial form?

**Comment by raziel-** [comment]
i can, though not before the end of next week, im afraid.

anyway, it still builds fine, so it can be merged before you get the logs, i believe?

**Review by sev- — APPROVED** [review]
Looks good to me, awaiting @raziel-

**Comment by dwatteau** [comment]
> @ccawley2011 I like the general idea, but it looks like the intentional PR #4557 hack is now gone, is it?
> 
> https://github.com/scummvm/scummvm/pull/6024/files#diff-c9485c5996fa68bdc00bc5b9967faf2af0381887cbd89e8d4cb576db6cdfc3be
> 
> The idea was to keep the `typedef signed long int32;` on win32, so that a frequent development platform + Github Actions target tests this `long` path. Having it at the Github Action stage, instead of the buildbot stage, helped catching and fixing some portability issues way sooner (“shifting left” in CI terms).
> 
> So I think that it would be nice to have the win32 keep the `typedef` exception as well. It has the side effect of helping the AmigaOS (and Nintendo DS?) target.

and here's another case where the current win32 behavior helped catching an int/int32 issue still in the PR phase, just a few hours ago:

https://github.com/scummvm/scummvm/pull/6050/commits/72690a0ea95810010d2de4ade332f3c240307184

Hence why I think it's a good idea to change the current PR a bit in order to keep this win32 exception

File: configure [hunk 1]
```diff
@@ -7328,23 +7221,7 @@ cat > config.h.new << EOF
...
-typedef signed $type_2_byte int16;
-typedef signed $type_4_byte int32;
-typedef signed $type_8_byte int64;
-#endif
-
-typedef $signed_type_ptr intptr;
-typedef $unsigned_type_ptr uintptr;
-
+/* TODO: What does this do? */
 #if defined(__APPLE__) && !defined(__ppc__)
```
Comment (mistydemeo) [inline configure:7225]: This dates back to 00242281006dd26204a3b438f1ecb38928bfb75f, which first defined 64-bit types in ScummVM. It's trying to prevent Apple's `_types/_uint64_t.h` from defining `uint64_t`; that file does:

```c
#ifndef _UINT64_T
#define _UINT64_T
typedef unsigned long long uint64_t;
#endif /* _UINT64_T */
```

Comment (mistydemeo) [reply configure:7225]: Did some testing on modern macOS (14.6.1), and I don't think this is necessary anymore. With this PR and the `#if defined(__APPLE__) && !defined(__ppc__)` block deleted, everything works just fine without redefined types errors.

Comment (dwatteau) [reply configure:7225]: Thanks for looking into this, @mistydemeo! I'm so happy to have the mighty Misty of Tigerbrew in our team, to know stuff like this! :smiley: 

Maybe something like i386 Tiger or Leopard needed this, but we don't have any official support for it, anyway. I do have a Leopard i386 VM, but no interest in reviving a ScummVM port for it, at the moment (one can just run the PPC binary through Rosetta 1 just fine). 

So I agree with removing this line. If it either breaks the (maintained) macOS 10.6+ build or the non-existing 10.4/10.5 i386 port, we might as well restore this line if it's proven to still be required there.

**Comment by raziel-** [comment]
@ccawley2011 

Sorry for the delay, here are the two logs.
Only the main binary has been compiled, but comparing them side by side will hopefully show what i meant with a "bunch-load" of new warnings.

Mind you, these new warnings could also pop up because they are not covered by the warning compression flag in configure anymore, but i'm not sure
(https://github.com/scummvm/scummvm/blob/master/configure#L2881C1-L2886C5)

`
		# use 'long' for ScummVM's 4 byte typedef, because AmigaOS
		# already typedefs (u)int32 as (unsigned) long and suppress
		# those noisy format warnings caused by the 'long' 4 byte
		append_var CXXFLAGS "-Wno-format"
		type_4_byte='long'
`

[console_log_current.txt](https://github.com/user-attachments/files/16728083/console_log_current.txt)
[console_log_new.txt](https://github.com/user-attachments/files/16728085/console_log_new.txt)

File: common/scummsys.h [hunk 2]
```diff
@@ -480,57 +480,33 @@
...
-		  defined(_M_ARM64)
-
-typedef int64 intptr;
-typedef uint64 uintptr;
 
+	typedef uint8_t uint8;
+	typedef int8_t int8;
+	typedef uint16_t uint16;
+	typedef int16_t int16;
+#if defined(__MORPHOS__) || defined(__amigaos4__)
```
Comment (bluegr) [inline common/scummsys.h:494]: If I understand it correctly, this is what @dwatteau is proposing, in order to keep the existing type hack:

```suggestion
// HACK: Some ports, such as NDS and AmigaOS, are not frequently
// tested during development, but cause frequent buildbot failures
// because they need to use 'long' for int32. Windows 32-bit
// binaries have this nice property of being easy to build, having
// a 32-bit 'long' too, *and* being frequently tested (incl. Github
// Actions). We want to catch this case as early and frequently
// as possible, so Win32 is probably the best candidate for this...
#if (defined(WIN32) && !defined(_WIN64)) || defined(__MORPHOS__) || defined(__amigaos4__)
```

**Comment by ccawley2011** [comment]
> Addendum: What do i have to do to test it without the "workaround"?

To test without the workaround, try removing `|| defined(__amigaos4__)` from line 494 in `common/scummsys.h` and see if it still compiles correctly.

File: common/scummsys.h (hunk 2 above)
Comment (bluegr) [reply common/scummsys.h:494]: Just talked with @ccawley2011, and this block is meant to be used as a temporary workaround, as stated in the original description

**Comment by raziel-** [comment]
@ccawley2011 

will do, thank you

**Comment by bluegr** [comment]
@dwatteau: having talked with @ccawley2011, theoretically, with these changes, we shouldn't need the Windows hack anymore. So, it will be rendered obsolete

**Comment by dwatteau** [comment]
> @dwatteau: having talked with @ccawley2011, theoretically, with these changes, we shouldn't need the Windows hack anymore. So, it will be rendered obsolete.
> 
> If we do need to test these types, we can create another dummy platform in buildbot, and either enforce the hack via a define, or pass it as a parameter:
> 
> ```
> -D__UINT32_TYPE__="unsigned long"
> ```

Ok thank you for the explanation.

Sure, if the NDS and AmigaOS don’t have any int/int32 difference anymore then the win32 hack has no purpose anymore indeed.

Has it been confirmed with a test that the NDS/AmigaOS targets indeed do not have this issue anymore, with this PR? One test could be to undo of the recent int/int32 engine commit fix in the Git log for example

**Comment by raziel-** [comment]
@dwatteau

I'm at work, if you tell me exactly what i have to   change, I'll run a build with that and report back asap (weekend)

**Comment by dwatteau** [comment]
Thanks @raziel-. Well, I actually tried replicating what I had in mind, with our Docker toolchain…

@ccawley2011: here's what I see:

```sh
git checkout your-current-pr
git revert 8d07b7d7d74306bbe67e1cf69b1516a4a87ab9f6 # locally undo a recent int/int32 mismatch fix, to see if the current PR fixes this use-case
./devtools/docker.sh toolchains/amigaos4 # dated "2 months ago" if pulled from scratch, in case this matters
./configure --host=ppc-amigaos --enable-plugins --default-dynamic --enable-detection-dynamic --disable-all-engines --disable-detection-full --enable-engine=qdengine

make -j$(nproc)
```

this gives:

```
...
engines/qdengine/system/graphics/gr_tile_animation.cpp: At global scope:
engines/qdengine/system/graphics/gr_tile_animation.cpp:267:6: error: no declaration matches 'void QDEngine::grTileAnimation::drawFrame(const QDEngine::Vect2i&, int32, int32) const'
  267 | void grTileAnimation::drawFrame(const Vect2i &position, int32 frame_index, int32 mode) const {
      |      ^~~~~~~~~~~~~~~
In file included from engines/qdengine/system/graphics/gr_tile_animation.cpp:27:
./engines/qdengine/system/graphics/gr_tile_animation.h:73:14: note: candidates are: 'void QDEngine::grTileAnimation::drawFrame(const QDEngine::Vect2i&, int, float, int) const'
   73 |         void drawFrame(const Vect2i &position, int frame_index, float angle, int mode = 0) const;
      |              ^~~~~~~~~
./engines/qdengine/system/graphics/gr_tile_animation.h:72:14: note:                 'void QDEngine::grTileAnimation::drawFrame(const QDEngine::Vect2i&, int, int) const'
   72 |         void drawFrame(const Vect2i &position, int frame_index, int mode = 0) const;
      |              ^~~~~~~~~
./engines/qdengine/system/graphics/gr_tile_animation.h:37:7: note: 'class QDEngine::grTileAnimation' defined here
   37 | class grTileAnimation {
      |       ^~~~~~~~~~~~~~~
make: *** [Makefile.common:177: engines/qdengine/system/graphics/gr_tile_animation.o] Error 1
```

i.e. AmigaOS still needs us to take care of the int/int32 differences?

If I try removing the `if defined(__MORPHOS__) || defined(__amigaos4__)` part from scummsys.h, then I get the following error:

```
    C++      backends/platform/sdl/amigaos/amigaos-main.o
In file included from /usr/local/amigaos4/ppc-amigaos/SDK/include/include_h/utility/utility.h:12,
                 from /usr/local/amigaos4/ppc-amigaos/SDK/include/include_h/proto/exec.h:13,
                 from ./backends/fs/amigaos/amigaos-fs.h:29,
                 from backends/platform/sdl/amigaos/amigaos-main.cpp:26:
/usr/local/amigaos4/ppc-amigaos/SDK/include/include_h/exec/types.h:93:23: error: conflicting declaration 'typedef long unsigned int uint32'
   93 | typedef unsigned long uint32;
      |                       ^~~~~~
In file included from backends/platform/sdl/amigaos/amigaos-main.cpp:22:
./common/scummsys.h:514:26: note: previous declaration as 'typedef uint32_t uint32'
  514 |         typedef uint32_t uint32;
      |                          ^~~~~~
In file included from /usr/local/amigaos4/ppc-amigaos/SDK/include/include_h/utility/utility.h:12,
                 from /usr/local/amigaos4/ppc-amigaos/SDK/include/include_h/proto/exec.h:13,
                 from ./backends/fs/amigaos/amigaos-fs.h:29,
                 from backends/platform/sdl/amigaos/amigaos-main.cpp:26:
/usr/local/amigaos4/ppc-amigaos/SDK/include/include_h/exec/types.h:94:24: error: conflicting declaration 'typedef long int int32'
   94 | typedef   signed long  int32;
      |                        ^~~~~
In file included from backends/platform/sdl/amigaos/amigaos-main.cpp:22:
./common/scummsys.h:515:25: note: previous declaration as 'typedef int32_t int32'
  515 |         typedef int32_t int32;
      |                         ^~~~~
    C++      base/test_new_standards.o
    C++      base/main.o
make: *** [Makefile.common:177: backends/platform/sdl/amigaos/amigaos-main.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by raziel-** [comment]
I'll try to redo what you did (not sure if *revert* is working on my local git tool)...but i don't think it will show anything different...while i might have a newer toolchain, the difference is probably marginal...

so, you guys decide if you want to wait for my feedback or just go ahead and merge like you see fit :-)

thanks a lot

**Comment by bluegr** [comment]
As a reference, AmigaOS types

https://wiki.amigaos.net/wiki/Fundamental_Types

File: common/scummsys.h (hunk 2 above)
Comment (lephilousophe) [reply common/scummsys.h:494]: Sadly, this cannot be removed and this is by no means a temporary workaround.

AmigaOS defines int32: `typedef   signed long  int32;`
But in the same time, newlib (their libc) defines int32_t: `typedef signed int int32_t;`
When we define int32, we must have a match with AmigaOS definition because we sometimes include system headers along our scummsys.h.

So, this PR can't fix the discrepancies problems we have on a regular basis.
To detect this before the buildbot, we need a platform which accepts `long int` as 32 bits sized int, this means a LLP64 platform and only Windows fits.
I am not sure we want to define it like this but maybe have a special define to enable it?

**Review by lephilousophe — COMMENTED** [review]
I have made some comments.
I also have started a buildbot on this PR to check for build errors.

I can already say that DS needs a fix as its headers don't define uintptr.
In fact, we can get rid of `SCUMMVM_DONT_DEFINE_TYPES` for DS port but I need a full build to make sure.

File: configure [hunk 3]
```diff
@@ -2844,11 +2761,6 @@ case $_host_os in
 			_plugins_default=static
 			_static_build=yes
 		fi
-		# use 'long' for ScummVM's 4 byte typedef, because AmigaOS
-		# already typedefs (u)int32 as (unsigned) long and suppress
-		# those noisy format warnings caused by the 'long' 4 byte
-		append_var CXXFLAGS "-Wno-format"
-		type_4_byte='long'
```
[the remark this answers is not in the document]
Comment (bluegr) [reply configure:2851]: @lephilousophe performed the change and readded `-Wno-format`, as suggested

**Comment by lephilousophe** [comment]
It's still building but one thing I notice is that there is a lot more of warnings related to formats.
Several ports seem to use `long int` for `int32_t` which triggers warnings when using the `%d` format specifier.

**Comment by raziel-** [comment]
@lephilousophe 

are those new warnings maybe similar or the same as the ones i posted in the logs earlier?

otoh i don't think i built any engines...

**Comment by lephilousophe** [comment]
After a first round of building with my patch for NDS, I get:
- a build failure on PSP (I just started a new round of building to see if this one is fixed by another patch)
- %d format warnings for 32 bits integers (where int32 is long int) : 3ds, AmigaOS (will vanish with change committed above), Dreamcast
- %ld format warnings for 64 bits integers (where int64 is long long int) : 3ds, AmigaOS (will vanish here too), Android ARM, Android x86, AppleTV, Debian x86, Gamecube, iOS ARM64, MacOS arm64, MacOS x86, MacOS x86_64, OD-GCW0, RPi, RiscOS, Vita, Wii, Windows 9x, Windows x86, Windows x86-64.

It seems that the %ld format problem is already here for 32 bits platforms and adds new warnings for MacOS 64 bits.

@raziel- yes, they are the same as the ones you posted 2 weeks ago.

File: common/scummsys.h (hunk 2 above)
Comment (dwatteau) [reply common/scummsys.h:494]: Thanks for your analysis!

Yes the win32 "hack" could be enabled only with a special opt-in flag. I chose to hardcode it back then, because I thought it could improve our internal coverage; i.e. some devs use MSVC and so having real daily users hit the int/int32 case before any CI triggers.

Just to help catching the issue as early as possible, so that someone doesn't start working on a new engine for months, before hitting CI/buildbot issues much later. The sooner you catch it the easier it is to fix it.

Also, if it's integrated into MSVC as well, it means that it may become easier to fix the issue, by iterating with the IDE, instead of "blind" Github Actions usage.

But we might as well have a buildbot having a similar hack or something, yes :)

**Comment by lephilousophe** [comment]
I just pushed some fixes for the PSP and removed the MacOS define.
I squashed all the changes to scummsys.h.

**Comment by raziel-** [comment]
@lephilousophe 

do you still need me to do a local build with and w/o the workaround?

reading your posts make it look like you figured everything out already 😀

**Comment by lephilousophe** [comment]
Yes, I don't think you need to do more tests.

To sum up:
- on 3ds, Dreamcast and PSP we get around 5K warnings because of int32_t does not match "%d",
- on 3ds, Android ARM, Android x86, AppleTV, Debian x86, Gamecube, iOS ARM64, MacOS arm64, MacOS x86, MacOS x86_64, OD-GCW0, PSP, RPi, RiscOS, Vita, Wii, Windows 9x, Windows x86, Windows x86-64 we get some hundreds of warnings because int64_t does not match "%ld".

The latest is already a (small) problem today.
The former is a quite big problem.

File: common/scummsys.h [hunk 4]
```diff
@@ -500,57 +479,33 @@
...
```
Comment (bluegr) [inline common/scummsys.h:493]:
```suggestion
#if defined(__3DS__) || defined(__amigaos4__) || defined(__DC__) || defined(__MORPHOS__) || defined(__PSP__)
```

This is another (cleaner) way of fixing all of these type-related warnings in these platforms. Will check

**Comment by lephilousophe** [comment]
So, after a long build, everything seems nominal now.
There are always the warnings related to uint64 but it's like today.

**Comment by bluegr** [comment]
Awesome work, everyone! This required a lot of work and feedback to finally get all the port defines working as intended
Thanks for your work @ccawley2011 and @lephilousophe
Thanks @dwatteau and @mistydemeo for your feedback
Thanks for testing @raziel- 

Merging

**Comment by sev-** [comment]
I am not very happy about this move.

First of all, it solves no existing problem.

But now, as a side effect, we have hundreds of warnings in the project. Who is going to fix them?
